version: '3.8'

services:
  web:
    build: .
    ports:
      - "8035:8035"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: >
      /bin/bash -c "
      flask run --host=0.0.0.0 --port=8035
      "
    networks:
      - airflow-net

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - airflow-net

  airflow-webserver:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW_ADMIN_USER=${AIRFLOW_ADMIN_USER}
      - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
      - ./scripts:/usr/local/airflow/scripts
      - ./data:/usr/local/airflow/data
    ports:
      - "8081:8080"
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for PostgreSQL...';
      until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}; do
        echo 'PostgreSQL is not ready...';
        sleep 1;
      done;
      echo 'PostgreSQL is ready!';
      airflow db init &&
      airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Admin --lastname Admin --role Admin --email ${AIRFLOW_ADMIN_EMAIL} &&
      airflow webserver --port 8080
      "
    networks:
      - airflow-net

  airflow-scheduler:
    build: .
    depends_on:
      - db
      - airflow-webserver
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
      - ./scripts:/usr/local/airflow/scripts
      - ./data:/usr/local/airflow/data
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for PostgreSQL...';
      until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}; do
        echo 'PostgreSQL is not ready...';
        sleep 1;
      done;
      echo 'PostgreSQL is ready!';
      airflow scheduler
      "
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge

volumes:
  pgdata:
    driver: local



  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "8080:80"